export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_MAKERS_SUCCESS = 'LOAD_MAKERS_SUCCESS';
export const CREATE_MAKER_SUCCESS = 'CREATE_MAKER_SUCCESS';
export const UPDATE_MAKER_SUCCESS = 'UPDATE_MAKER_SUCCESS';
export const DELETE_MAKER_SUCCESS = 'DELETE_MAKER_SUCCESS';

export const LOAD_WINES_SUCCESS = 'LOAD_WINES_SUCCESS';
export const CREATE_WINE_SUCCESS = 'CREATE_WINE_SUCCESS';
export const UPDATE_WINE_SUCCESS = 'UPDATE_WINE_SUCCESS';
export const DELETE_WINE_SUCCESS = 'DELETE_WINE_SUCCESS';